#! /bin/sh

# Install /usr/bin wrapper for SCLized executable.
# Copyright (C) 2017 Red Hat, Inc.
# Written by Pavel Raiskup <praiskup@redhat.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

die() { echo >&1 "$*" ; exit 1 ; }

test "$1" = _PROTECT_ \
    || die "this script can not be used directly, use macros from @MACROS@ in your package"

set -e

shift
buildroot="$1"    ; shift
scl="$1"          ; shift
root_bindir="$1"  ; shift
bindir="$1"       ; shift
executable="$1"   ; shift

wrapper="$buildroot$root_bindir/$executable"

mkdir -p "$buildroot$root_bindir"

cat <<EOF > "$wrapper"
#! /bin/sh

# Just a convenience script for running '$executable' from '$scl'
# collection, without the need to call 'scl enable $scl'.  Note that
# it is not a bug when this script causes RPM collision with some
# '$root_bindir/$executable' executable installed from different package.
#
# Generated by @GENERATOR@.

source scl_source enable $scl
exec "$bindir/$executable" "\$@"
EOF

chmod 755 "$wrapper"
